services:
  swyp-scraper:
    build: .
    container_name: keepit-scraper
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    shm_size: '2gb'
    init: true
    restart: always
